[package]
name = "pijama_ctx"
version = "0.1.0"
authors = ["Christian Poveda <git@christianpoveda.xyz>"]
edition = "2018"

[dependencies]
pijama_common = { path = "../pijama_common" }
pijama_ty = { path = "../pijama_ty" }
