[package]
name = "pijama_tycheck"
version = "0.1.0"
authors = ["The Pijama Project Developers"]
edition = "2018"

[dependencies]
thiserror = "1.0"
pijama_mir = {path = "../pijama_mir"}
pijama_ty = {path = "../pijama_ty"}
pijama_common = {path = "../pijama_common"}
