[package]
name = "pijama_machine"
version = "0.1.0"
authors = ["The Pijama Project Developers"]
edition = "2018"

[dependencies]
pijama_lir = {path = "../pijama_lir"}
pijama_common = { path = "../pijama_common" }
