[package]
name = "pijama_lir"
version = "0.1.0"
authors = ["The Pijama Project Developers"]
edition = "2018"

[dependencies]
pijama_hir = {path = "../pijama_hir"}
pijama_common = { path = "../pijama_common" }
pijama_ctx = { path = "../pijama_ctx" }
